### ISSUE TITLE
Show results as a map

### ISSUE THREAD

**Issue by douggreen** [twelvestepdrupal/twelvestepintergroup#30]

**Comment by twelvestepdrupal** [comment]
This is /mostly done/ with https://github.com/anondrupal/twelvestepintergroup/pull/32, https://github.com/anondrupal/twelvestepintergroup/pull/33, and https://github.com/anondrupal/twelvestepintergroup/pull/34.

f/u issues https://github.com/anondrupal/twelvestepintergroup/issues/35 and https://github.com/anondrupal/twelvestepintergroup/issues/36.
